# Generated by Django 5.0.6 on 2024-09-23 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completion Time')),
                ('desc', models.TextField(blank=True, verbose_name='Completion Description')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Scheduled Time')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Web.task')),
                ('task_type', models.CharField(choices=[('Work', 'Work'), ('Language', 'Language'), ('Study', 'Study')], max_length=50, verbose_name='Task Type')),
                ('completion_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.completionstatus', verbose_name='Completion Status')),
            ],
            bases=('Web.task',),
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, verbose_name='Day of Week')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.dailytask')),
            ],
        ),
    ]
