# Generated by Django 5.0.6 on 2024-10-10 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationWay', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('detection_results', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_labeled', models.BooleanField(default=False)),
                ('path', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('logType', models.IntegerField()),
                ('status', models.IntegerField()),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.dailytask', verbose_name='Task'),
        ),
        migrations.CreateModel(
            name='MonkeyDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('monkey_count', models.PositiveIntegerField(default=0)),
                ('verdict', models.IntegerField(default=0)),
                ('mark', models.JSONField(default=dict)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Web.image')),
            ],
        ),
    ]
