# Generated by Django 5.0.6 on 2024-10-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_config_image_systemlog_alter_weeklytask_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
